steps:
  - module_header:
      indent: 8
      sort: true
      separate_lists: true
      break_where: exports
      open_bracket: next_line

  - records:
      equals: "indent 8"
      first_field: "indent 8"
      field_comment: 2
      deriving: 8
      via: "indent 4"
      sort_deriving: true
      break_enums: true

  - simple_align:
      cases: always
      top_level_patterns: always
      records: always
      multi_way_if: always

  - imports:
      align: global
      list_align: after_alias
      pad_module_names: true
      long_list_align: inline
      empty_list_align: inherit
      list_padding: 4
      separate_lists: true
      space_surround: false
      post_qualify: false
      group_imports: true
      group_rules:
        - match: ".*"
          sub_group: "^[^.]+"

  - language_pragmas:
      style: vertical
      align: true
      remove_redundant: true
      language_prefix: LANGUAGE

  - tabs:
      spaces: 8

  - trailing_whitespace: {}

newline: native

cabal: true
